mutation AddExtensionStore($input: AddExtensionStoreInput!) {
  addExtensionStore(input: $input) {
    extensionStore {
      name
      indexUrl
      isLegacy
      signingKey
      badgeLabel
    }
  }
}

mutation RemoveExtensionStore($input: RemoveExtensionStoreInput!) {
  removeExtensionStore(input: $input) {
    extensionStore {
      indexUrl
    }
  }
}

mutation FetchExtensionCatalog($input: FetchExtensionsInput!) {
  fetchExtensions(input: $input) {
    extensions {
      pkgName
    }
  }
}

mutation ToggleExtensionInstall($input: UpdateExtensionInput!) {
  updateExtension(input: $input) {
    extension {
      pkgName
      isInstalled
    }
  }
}

mutation UpdateExtensions($input: UpdateExtensionsInput!) {
  updateExtensions(input: $input) {
    extensions {
      pkgName
      isInstalled
      hasUpdate
      versionName
    }
  }
}
