query GetSources {
  sources(first: 2000) {
    totalCount
    nodes {
      id
      name
      lang
      iconUrl
      supportsLatest
      isNsfw
      isConfigurable
      extension {
        pkgName
        isInstalled
      }
    }
  }
}

query GetSourcesByCondition($lang: String!) {
  sources(condition: { lang: $lang }, first: 2000) {
    totalCount
    nodes {
      id
      name
      lang
      iconUrl
      supportsLatest
      isNsfw
      isConfigurable
    }
  }
}

query GetInstalledExtensionLangs {
  extensions(condition: { isInstalled: true }, first: 2000) {
    totalCount
    nodes {
      pkgName
      lang
    }
  }
}
