query GetSources {
  sources {
    edges {
      node {
        id
        name
        lang
        iconUrl
        supportsLatest
        isNsfw
        extension {
          pkgName
          isInstalled
        }
      }
    }
  }
}

query GetSourcesByCondition($lang: String!) {
  sources(condition: { lang: $lang }) {
    edges {
      node {
        id
        name
        lang
        iconUrl
        supportsLatest
        isNsfw
      }
    }
  }
}

query GetInstalledExtensionLangs {
  extensions(condition: { isInstalled: true }) {
    edges {
      node {
        pkgName
        lang
      }
    }
  }
}
