query GetCategories {
  categories {
    nodes {
      id
      name
      order
    }
  }
}

query GetLibrary(
  $filter: MangaFilterInput
  $first: Int
  $after: Cursor
) {
  mangas(filter: $filter, first: $first, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      title
      thumbnailUrl
      unreadCount
      downloadCount
      lastReadChapter {
        id
      }
      categories {
        nodes {
          id
        }
      }
    }
  }
}

