query GetMangaDetails($id: Int!) {
  manga(id: $id) {
    id
    title
    author
    artist
    description
    thumbnailUrl
    status
    genre
    inLibrary
    categories {
      edges {
        node {
          id
        }
      }
    }
    source {
      name
    }
    chapters {
      edges {
        node {
          id
          name
          chapterNumber
          isRead
          isBookmarked
          isDownloaded
          uploadDate
          scanlator
        }
      }
    }
  }
}
